# Generated by Django 4.1.5 on 2023-01-07 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('ratings', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cancelation_policy', models.CharField(max_length=300)),
                ('website', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('main_photo', models.ImageField(upload_to='')),
                ('gender_specific', models.CharField(choices=[('MEN', 'men'), ('WOMAN', 'women')], default='MEN', max_length=10)),
            ],
        ),
    ]
