# Generated by Django 4.1.5 on 2023-01-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='main_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
